//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_tag
    {
        public string id_a_tag { get; set; }
        public string href { get; set; }
        public int id_url { get; set; }
        public string title { get; set; }
        public string text_value { get; set; }
        public string xpath { get; set; }
    
        public virtual Url Url { get; set; }
    }
}
