//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Element()
        {
            this.Input_testcase = new HashSet<Input_testcase>();
        }
    
        public string id_element { get; set; }
        public int id_url { get; set; }
        public string name { get; set; }
        public string class_name { get; set; }
        public string tag_name { get; set; }
        public string type { get; set; }
        public string value { get; set; }
        public string href { get; set; }
        public string title { get; set; }
        public string id_form { get; set; }
        public Nullable<double> minlength { get; set; }
        public Nullable<double> maxlength { get; set; }
        public Nullable<bool> required { get; set; }
        public Nullable<bool> read_only { get; set; }
        public string max_value { get; set; }
        public string min_value { get; set; }
        public Nullable<bool> multiple { get; set; }
        public string xpath { get; set; }
    
        public virtual Url Url { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input_testcase> Input_testcase { get; set; }
    }
}
