//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element_test
    {
        public string id_testcase { get; set; }
        public int id_url { get; set; }
        public string id_element { get; set; }
        public string xpath { get; set; }
        public string xpath_full { get; set; }
        public string value_return { get; set; }
        public string value_test { get; set; }
        public string class_name { get; set; }
    
        public virtual Test_case Test_case { get; set; }
    }
}
