//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Input_elements
    {
        public string id_input { get; set; }
        public string name { get; set; }
        public string class_name { get; set; }
        public string type { get; set; }
        public string value { get; set; }
        public string id_form { get; set; }
        public Nullable<int> minlength { get; set; }
        public Nullable<int> maxlength { get; set; }
        public Nullable<bool> required { get; set; }
        public Nullable<bool> @readonly { get; set; }
        public Nullable<float> max { get; set; }
        public Nullable<float> min { get; set; }
        public Nullable<bool> multiple { get; set; }
    }
}
