//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElementDBEntities : DbContext
    {
        public ElementDBEntities()
            : base("name=ElementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<Element_test> Element_test { get; set; }
        public virtual DbSet<Form_elements> Form_elements { get; set; }
        public virtual DbSet<Input_testcase> Input_testcase { get; set; }
        public virtual DbSet<Redirect_url> Redirect_url { get; set; }
        public virtual DbSet<Test_case> Test_case { get; set; }
        public virtual DbSet<Url> Urls { get; set; }
    }
}
